name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: fmeriaux/setup-java@sbt-cache
      with:
        java-version: 1.8
        distribution: zulu
        cache: sbt
    - name: Run tests
      run: sbt test
    - name: Run sbt package
      run: sbt package
